# Generated by Django 6.0.5 on 2026-05-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_run_trajectory'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
