# Generated by Django 5.2.14 on 2026-06-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_add_uuid_to_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='live_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
