# Generated by Django 6.0.5 on 2026-08-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_add_live_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='architecture',
            field=models.CharField(db_index=True, default='react', max_length=40),
        ),
        migrations.AddField(
            model_name='run',
            name='budget_exhausted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='model_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='run',
            name='token_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='token_usage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
